TURBION_TEST_OPENID_SERVER_HOST = "localhost"
TURBION_TEST_OPENID_SERVER_PORT = 8080
TURBION_TEST_OPENID_SERVER_NICK = "daev"

TURBION_OPENID_TRUST_URL = None

TURBION_OPENID_IDENTITY_URL = None
TURBION_OPENID_IDENTITY_PROFILE = None
